name: Publish Pages
on:
  push:
      branches: 'master'
      paths: 'src/**'
  workflow_dispatch:

jobs:
  Publish-Pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          npm run lint
          npm run build

      - name: Only keep dist
        run: |
          mkdir ../tmpDist
          mv dist/* ../tmpDist
          rm -fr * .github .eslintrc.json .gitignore
          mv ../tmpDist/* .

      - name: Publish to Pages
        uses: EndBug/add-and-commit@v8
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 'Publish to Github Pages'
          add: .
          new_branch: gh-pages
